// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unifesp.teste.model;

import br.unifesp.teste.model.Celular;

privileged aspect Celular_Roo_JavaBean {
    
    public String Celular.getNumero() {
        return this.Numero;
    }
    
    public void Celular.setNumero(String Numero) {
        this.Numero = Numero;
    }
    
}
