// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package br.unifesp.teste.model;

import br.unifesp.teste.model.Pessoa;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Pessoa_Roo_Configurable {
    
    declare @type: Pessoa: @Configurable;
    
}
